
# Input/Output
input: null    # Path to the input VCF file
output: null   # Directory to store output files
db_bcf: null   # Path to the database BCF file

# Resource files
chr_add: 'tests/data/chr_add.txt'
reference: 'tests/data/reference.fa'
vep_cache: 'tests/data/vep_cache'

# Tool paths and container settings
container_engine: '/usr/bin/docker'
container_bind: '-v /mnt/data:/mnt/data'
vep_container: 'ensemblorg/ensembl-vep:release_113.0'
echtvar_path: '/mnt/data/apps/echtvar/echtvar'

# Tool settings
vep_max_chr_parallel: 2
vep_max_forks: 2

# Workflow control
db_mode: false