# Input/Output
input: null    # Path to the input VCF file
output: null   # Directory to store output files
db_bcf: null   # Path to the database BCF file

# Resource files
chr_add: '/mnt/data/samples/chr_add.txt'
reference: '/mnt/data/resources/reference/ucsc/hg19_canonical.fa.gz'
vep_cache: '/mnt/data/apps/ensembl-vep/113/cachedir/'

# Tool paths
apptainer_path: '/usr/bin/apptainer'
apptainer_bind: '/mnt/data:/mnt/data'
vep_container: '/mnt/data/apps/ensembl-vep/113/vep.sif'
echtvar_path: '/mnt/data/apps/echtvar/echtvar'

# Tool settings
vep_max_chr_parallel: 4
vep_max_forks: 4

# Workflow control
db_mode: false